### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by PandaWhoCodes** [Cartman720/PySitemap#1]
Tried testing it. Didn't work.

**Comment by Cartman720** [comment]
Hi @reach2ashish 

Can you provide more information about any errors or how had you run program, since I have tried it and could not find any errors.

**Comment by PandaWhoCodes** [comment]
python3 main.py --url https://focusinfotech.com

**Comment by Cartman720** [comment]
Can you try again and let me know if there is an errors again.
Thanks!
