### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by iyosayi0x** [Cartman720/PySitemap#11]
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.finstead.com'. (_ssl.c:1129)>

Valid webistes keep on showing 404 error , so i decided to print out the exception and got this

**Comment by Cartman720** [comment]
Well, www.finstead.com doesn't work. Have you tried another host i.e. google.com?

**Comment by iyosayi0x** [comment]
It works for some other hosts like , GitHub.com , freelancer.com , ... e.t.c

Is there anyway to fix the SSL error ? 

Because it keeps returning 404 error for websites that exists
